default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  <<: *default
  host: 127.0.0.1
  port: <%= ENV.fetch('DATABASE_PORT') { '3306' } %>
  username: root
  password: <%= ENV.fetch('DATABASE_PASSWORD') { '' } %>

development:
  <<: *local
  database: tst_assignment_development

test:
  <<: *local
  database: tst_assignment_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
